syntax = "proto3";
package orchestrator.register.v1;
option go_package = "github.com/Norzuiso/protocol/gen/go/orchestrator/register/v1;registerv1";

message User {
    string id = 1;
    string name = 2;
}

message Message {
    string sender_id = 1;
    string receiver_id = 2;
    string content = 3;
}

message Connect {
    User user = 1;
    repeated string user_connection_ids = 2;
    bool active = 3;
}

message Close {}

service Broadcast{
    rpc CreateStream(Connect) returns (stream Message);
    rpc BroadcastMessage(Message) returns (Close)
}