syntax = "proto3";
package orchestrator.register.v1;
option go_package = "github.com/Norzuiso/protocol/gen/go/orchestrator/register/v1;registerv1";

option java_multiple_files = true;
option java_package = "com.orchestrator.v1.register";
option java_outer_classname = "RegisterServiceProto";

import "google/protobuf/any.proto";


enum MessageType {
    MESSAGE_TYPE_DEFAULT = 0;
    MESSAGE_TYPE_ERROR = 1;

    // Orquestrator send request to have the event from a client
    MESSAGE_TYPE_RECOLECT_EVENT = 2;

    // Client send an event to the orquestrator
    MESSAGE_TYPE_SEND_EVENT = 3;

    // Once the orquestrator recolect an event from a client. it sends the event 
    // to other clients that apply/react 
    MESSAGE_TYPE_APPLY_EVENT =4;
    
    // Open stream to have an active connection with the orquestrator. This is used to have communication between clients using orquestrator as intermediario
    MESSAGE_TYPE_OPEN_STREAM = 5;

    MESSAGE_TYPE_CLIENT_RESPONSE = 6;

    // This type of message is send it from the orquestrator. 
    // This means that the client sent a not allow it type of message
    MESSAGE_TYPE_ERROR_PHASE=7;
    
    MESSAGE_TYPE_CLIENT_STATUS=8;
}

message Message {
    int64 sender_id = 1;
    string content = 2;
    optional MessageType messageType = 3;
    optional float epoch = 4;
    map<string, google.protobuf.Any> attributes = 5;
}

message Client {
    int64 id = 1;
    string name = 2;
    optional string description = 3;
    int64 seed = 4; // the seed could have a value but if no the orchestrator assign one
}

message ConnectionRequest {
    Client client = 1;
}

message ConnectionResponse {
    Client client = 1;
}

message RegisterConnectionRequest {
    int64 from_id = 1;
    repeated int64 to_id = 2;
    map<string, google.protobuf.Any> attributes = 3;
}

message RegisterConnectionResponse {
    string response = 1;
}

service Broadcast{
    rpc ConnectClient(ConnectionRequest) returns (ConnectionResponse);
    rpc ClientToClientMessage(stream Message) returns (stream Message);
    rpc RegisterConnection(RegisterConnectionRequest) returns (RegisterConnectionResponse);
}